from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import (
    RegisterView,
    TeamViewSet,
    MembershipListCreateView,
    MembershipDetailView,
    TaskListCreateView,
    TaskDetailView
)

# Create router and register TeamViewSet
router = DefaultRouter()
router.register(r'teams', TeamViewSet, basename='team')

urlpatterns = [
    # Auth endpoints
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Team endpoints (generated by the router)
    path('', include(router.urls)),

    # Membership endpoints (nested under a team)
    path('teams/<int:team_pk>/members/',
         MembershipListCreateView.as_view(), name='membership-list-create'),
    path('teams/<int:team_pk>/members/<int:pk>/',
         MembershipDetailView.as_view(), name='membership-detail'),

    # Task endpoints
    path('tasks/', TaskListCreateView.as_view(), name='task-list-create'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
]